import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Header from "../componentes/header";

const franklin = Libre_Franklin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>BTCA</title>
        <link rel="icon" href="/images/LogoBTCA-PNG.png"></link>
      </head>
      <body className="bg-[#1b1a16]">
       <Header/>
       <main className={franklin.className}>{children}</main>
      </body>
    </html>
  );
}
